### ISSUE TITLE
Bundle install is dog slow

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-integration#2]
Right now the integration tests require bundle install which is literally dog slow. It makes our tests painful. Not only that but we also have to start the server.

If we could just remove the need for the long wait for every bundle install, that would be much better. Maybe tell bundler to grab the dependencies locally or something. If this is the only way, I guess it's ok because these will typically be run by Hudson.

**Comment by achiurizo** [comment]
@nesquena im looking into this issue to. another thing that can help is to specify each lib version to speed up the fetching process

**Comment by DAddYE** [comment]
Any better idea? With jenkins Im able to run test in concurrency but the main problem is that we need to adjust our tests to use a random? port for the web server. @nesquena any idea?

**Comment by nesquena** [comment]
Yea I don't think we can solve this easily. Closing for now. Random port is interesting, we should do that though.
