### ISSUE TITLE
Add redis, memcache, mongo and couchdb

### ISSUE THREAD

**Issue by DAddYE** [padrino/padrino-integration#5]
I need to install on my server:
- redis (test cache)
- memcache (test cache)
- mongo (test padrino admin)
- couchdb (test padrino admin)

**Comment by nesquena** [comment]
Yes, good idea to install of the components. This project will be great. Eventually we can test enough that if the tests pass here then we know our framework works for a solid release.

**Comment by DAddYE** [comment]
Done!

**Comment by nesquena** [comment]
Awesome!
