### ISSUE TITLE
Slim error: (erb):6: warning: found = in conditional, should be ==

### ISSUE THREAD

**Issue by WaYdotNET** [padrino/padrino-integration#9]
```
(erb):6: warning: found = in conditional, should be ==
```

it's false .. the line is

```
ENV['BUNDLE_GEMFILE'] = File.join(apptmp, "Gemfile")
```

**Comment by dariocravero** [comment]
Mmm, are you sure? It stopped complaining once I pushed [this change](https://github.com/padrino/padrino-framework/commit/b4de89b9ecc34fddb5169cd329fee075873a2a02#L7R6). Reopen if it's still there.
